### ISSUE TITLE
GCC can't build PlayRho on Windows

### ISSUE THREAD

**Issue by Adevald** [louis-langholtz/PlayRho#385] opened 2021-01-25 07:35 UTC
### Expected/Desired Behavior or Experience:
Everything should compile fine

### Actual Behavior:
GCC compiler doesnt see `__FUNCSIG__` in TypeInfo.hpp

### Additional info
Here is compiler output.
```
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is GNU 8.3.0
[cmake] -- The CXX compiler identification is GNU 8.3.0
... 

[build] K:/!Programming/!projects/vehicle-phys-prototype/third-party/PlayRho/PlayRho/Common/TypeInfo.hpp: In function 'constexpr const char* playrho::detail::GetNameForTypeInfo()':
[build] K:/!Programming/!projects/vehicle-phys-prototype/third-party/PlayRho/PlayRho/Common/TypeInfo.hpp:41:12: error: '__FUNCSIG__' was not declared in this scope
[build]      return __FUNCSIG__;
[build]             ^~~~~~~~~~~
[build] K:/!Programming/!projects/vehicle-phys-prototype/third-party/PlayRho/PlayRho/Common/TypeInfo.hpp: In instantiation of 'constexpr const char* const playrho::TypeInfo<void>::name':
[build] K:/!Programming/!projects/vehicle-phys-prototype/third-party/PlayRho/PlayRho/Common/TypeInfo.hpp:115:19:   required from 'constexpr playrho::TypeID playrho::GetTypeID() [with T = void; playrho::TypeID = playrho::detail::IndexingNamedType<const char* const*, playrho::TypeIdentifier>]'
[build] K:/!Programming/!projects/vehicle-phys-prototype/third-party/PlayRho/PlayRho/Collision/Shapes/Shape.hpp:331:74:   required from here
[build] K:/!Programming/!projects/vehicle-phys-prototype/third-party/PlayRho/PlayRho/Common/TypeInfo.hpp:63:70:   in 'constexpr' expansion of 'playrho::detail::GetNameForTypeInfo<void>()'
[build] K:/!Programming/!projects/vehicle-phys-prototype/third-party/PlayRho/PlayRho/Common/TypeInfo.hpp:63:34: error: 'constexpr' call flows off the end of the function
[build]      static constexpr const char* name = detail::GetNameForTypeInfo<T>();
[build]                                   ^~~~
[build] make.exe[2]: *** [CMakeFiles/vehicle-phys-prototype.dir/build.make:83: CMakeFiles/vehicle-phys-prototype.dir/src/main.cpp.obj] Error 1
[build] make.exe[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/vehicle-phys-prototype.dir/all] Error 2
[build] make.exe: *** [makefile:103: all] Error 2
```

### Steps to Reproduce the Actual Behavior:
Try to use GCC 8.3.0 to build PlayRho

**Comment by ninnghazad** [comment] 2021-01-28 20:06
You could try adding this to some header:
```
#ifdef __FUNCSIG__
#define __FUNCSIG__ __PRETTY_FUNCTION__
#endif
```
As i think __FUNCSIG__ is a MSVC thing and __PRETTY_FUNCTION__ a *nix thing. You seem to be using gcc on windows - which may be why this happens.

**Comment by Adevald** [comment] 2021-01-29 04:46
> 
> 
> You could try adding this to some header:
> 
> ```
> #ifdef __FUNCSIG__
> #define __FUNCSIG__ __PRETTY_FUNCTION__
> #endif
> ```
> 
> As i think **FUNCSIG** is a MSVC thing and **PRETTY_FUNCTION** a *nix thing. You seem to be using gcc on windows - which may be why this happens.

It doesnt wirk for gcc either, so i just start to use msvc.

**Comment by louis-langholtz** [comment] 2021-03-05 19:32
@Adevald Thank you for your interest in this repository and for reporting this issue! I'm sorry that this has occurred.

On my looking at the code, it looks like the problem is [line 40](https://github.com/louis-langholtz/PlayRho/blob/master/PlayRho/Common/TypeInfo.hpp#L40) where the pre-processor code detects `_WIN32` instead of something that says MSVC is being used like `_MSC_VER`. That sounds like what you and @ninnghazad are indicating.

I'll work on a fix.

**Comment by louis-langholtz** [comment] 2021-03-05 21:06
I believe commit 83acf81298a6f7f8f5d586b6b02a701aae6bc3b4, which I just merged into master, should fix this problem. If you can try again with GCC 8.3 on Windows, please let me know whether the latest code works now or not. Thanks again!

**Comment by louis-langholtz** [comment] 2021-03-09 22:42
Haven't heard any more about this issue. Gonna assume this is fixed with the mentioned commit.

@Adevald If you get the chance to try the fix out and it doesn't work, please add to this issue what you find and we'll reopen this issue as necessary.

**Closed by louis-langholtz** 2021-03-09 22:42 UTC
Labels: bug, windows
